### ISSUE TITLE
Upgrading to 2.0.16 breaks static site generator

### ISSUE THREAD

**Issue by kyranb** [justkidding96/statamic-aardvark-seo#100]
Each page has the following error:

[✘] /privacy-policy (Call to a member function raw() on string)

**Comment by globalexport** [comment]
The stacktrace starts at
https://github.com/WithCandour/statamic-aardvark-seo/blob/e658bd5b614838d03c8042341956d70a55e17ff9/src/Parsers/PageDataParser.php#L49

$value is the string.

**Comment by globalexport** [comment]
I tested the downgrade to 2.0.14 and got rid of the errors.

**Comment by globalexport** [comment]
Hi Andrew, 

Why did you close the issue? Has it been resolved?

**Comment by globalexport** [comment]
Sorry, I missed the commit hash. Thanks a lot! :)

**Comment by AndrewHaine** [comment]
Hi @globalexport ,

Yep, we've identified and applied the fix, apologies I think GitHub closed it prematurely since I mentioned it in the commit message. The fix will be released in 2.0.17 later today.

The issue was that we were missing the blueprint fields since our listener was excluding them if the app was running in the console, I've removed this check which has fixed the issue and I don't see a use case where having the blueprints when running in the console would cause an issue - this might be revisited in the future though when we have more info.

Thanks,
Andrew
