### ISSUE TITLE
Redirects not picked up with git

### ISSUE THREAD

**Issue by ottz0** [justkidding96/statamic-aardvark-seo#141]
I have added my redirects on my testing server but the file is not getting picked up with git. So when i'm pushing and pulling my site, i'm losing the redirects.

I'm using the paid version of Ardvark SEO 2.0.28 and have seen issue thread  #125.

I've added these lines into my .gitignore but still not picking up changes 

```
!.gitignore
!/addons/aardvark-seo
!/statamic/addons/aardvark-seo
```

**Comment by ottz0** [comment]
fix as per @devonbeard was to add to git git add storage/statamic/addons/aardvark-seo/* -f.  

```
!.gitignore
!/addons/aardvark-seo
!/statamic/addons/aardvark-seo
```

did not work

**Comment by aidanweltner** [comment]
@ottz0 I know this issue is a little stale but I thought I was having a similar issue. I realized I could put the `.gitignore` rules in a more specific file. Make sure the rules are in the `storage/statamic/.gitignore` file. If that still doesn't work add the following to to the `paths` array in your `config/statamic/git.php` file
```
storage_path('statamic/addons/aardvark-seo'),
```

**Comment by joshuanoyes** [comment]
> Make sure the rules are in the storage/statamic/.gitignore file

This is the correct approach according to the [documentation](https://github.com/WithCandour/statamic-aardvark-seo/blob/master/DOCUMENTATION.md) - @ottz0 if this did not resolve the problem for you please reopen this issue. Thanks!
