### ISSUE TITLE
SEO Tab doesn't display until the page is published.

### ISSUE THREAD

**Issue by mattmultiplied** [justkidding96/statamic-aardvark-seo#93]
https://www.loom.com/share/4c0f1b527d264240b62dd6320c681b01

Would be great if the SEO tab was visible prior to publishing, so that it doesn't need to be added once the page has gone live

**Comment by AndrewHaine** [comment]
This one I believe is related to [the following lines](https://github.com/WithCandour/statamic-aardvark-seo/blob/master/src/Listeners/AppendEntrySeoFieldsListener.php#L18-L21) in the code which adds the fields to the CMS. Currently we're checking that an entry exists before appending the fields (in order to avoid adding the fields to the blueprint editor) - we'll look into whether or not there may be a better check we can do here.

**Comment by AndrewHaine** [comment]
Keeping an eye on [this PR](https://github.com/statamic/cms/pull/4086) which looks like it might offer this functionality for us

**Comment by aerni** [comment]
This would solve your problem: https://github.com/statamic/ideas/issues/641

**Comment by aerni** [comment]
Thought you might be interested in implementing it this way: https://github.com/statamic/ideas/issues/550

**Comment by AndrewHaine** [comment]
Thanks @aerni and @mattmultiplied ,

The above solution has been implemented and released in 2.0.16 :)

Thanks,
Andrew
